#2
string='it goes as - ringa ringa roses'
sub='ringa'
a=string.find(sub)
print(a)
b=string.find(sub,15,22)
print(b)
c=string.find(sub,15,25)
print(c)
#3
string='abc123'
string2='hello'
string3='12345'
string4=' '
a=string.isalnum()
b=string2.isalnum()
c=string3.isalnum()
d=string4.isalnum()
print(a)
print(b)
print(c)
print(d)
#4
string='abc123'
string2='hello'
string3='12345'
string4=' '
a=string.isalpha()
b=string2.isalpha()
c=string3.isalpha()
d=string4.isalpha()
print(a)
print(b)
print(c)
print(d)
#5
string='abc123'
string2='hello'
string3='12345'
string4=' '
a=string.isdigit()
b=string2.isdigit()
c=string3.isdigit()
d=string4.isdigit()
print(a)
print(b)
print(c)
print(d)
#6
string='hello'
string2='THERE'
string3='Goldy'
a=string.islower()
b=string2.islower()
c=string3.islower()
print(a)
print(b)
print(c)
#7
string='   '
string2=''
a=string.isspace()
b=string2.isspace()
print(a)
print(b)
#8
string='HELLO'
string2='There'
string3='goldy'
string4='U123'
string5='123f'
a=string.isupper()
b=string2.isupper()
c=string3.isupper()
d=string4.isupper()
e=string5.isupper()
print(a)
print(b)
print(c)
print(d)
print(e)